config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/profskipulag/SS5401:
      branch: main
      repo: https://github.com/profskipulag/SS5401
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/profskipulag/SS5401 git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-bistre-hound.sh
        container: qc.acc_seedy-lilac-chinchilla
  QC.Doc:
    repos:
      github.com/profskipulag/SS5401 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-olivine-fox.sh
        container: qc.doc_blurry-cerise-slug
      github.com/profskipulag/SS5401 git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-emerald-akbash.sh
        container: qc.doc_surly-khaki-mastiff
      github.com/profskipulag/SS5401 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ochre-chicken.sh
        container: qc.doc_bumpy-amethyst-fly
  QC.Lic:
    repos:
      github.com/profskipulag/SS5401 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-brass-lobster.sh
        container: qc.lic_queasy-teal-otter
  QC.Sec:
    repos:
      github.com/profskipulag/SS5401 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-turquoise-rattlesnake.sh
        container: qc.sec_muggy-sapphire-boar
  QC.Sty:
    repos:
      github.com/profskipulag/SS5401 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-mustard-shrew.sh
        container: qc.sty_cozy-alizarin-russel
      github.com/profskipulag/SS5401 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-aquamarine-tarantula.sh
        container: qc.sty_beady-aqua-pig
  QC.Uni:
    repos:
      github.com/profskipulag/SS5401 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.randy-rose-harrier.sh
        container: qc.uni_skinny-maroon-kingfisher
  QC.Ver:
    repos:
      github.com/profskipulag/SS5401 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-linen-orangutan.sh
        container: qc.ver_flimsy-periwinkle-llama
timeout: 5400
